ruta_carrito = "../base_de_datos/carrito.json"
ruta_centros = "../base_de_datos/centros.json"
ruta_usuarios = "../base_de_datos/cuentas_usuarios.json"
ruta_historial_por_carnet = "../base_de_datos/historial_por_carnet.json"
ruta_historial_recibos = "../base_de_datos/historial_recibos.json"
ruta_materiales = "../base_de_datos/materiales.json"
ruta_sedes = "../base_de_datos/sedes.json"